import Head from 'next/head'
import Image from 'next/image'
import { CityEvChart } from '../src/component/cityEvChart'
import { DrawChart } from '../src/component/DrawChart'
import GetList from '../src/component/GetList'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
{/* 
      <GetList />
       */}
{/* 
      <div style={{width: '80%', margin: '0 auto'}} >
        <DrawChart />
      </div>
    */}
      <div style={{width: '80%', margin: '0 auto'}} >
        <CityEvChart />
      </div>
    </div>
  )
}
